import type { Metadata } from "next";
import {Roboto_Mono} from "next/font/google"
import "./globals.css";
import "./reset.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RobotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RobotoMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
